spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  redis:
    # redis缓存配置信息
    host: 39.108.37.4
    port: 6379
  datasource:
    # mysql数据库配置信息
    url: jdbc:mysql://39.108.37.4:3306/db_fictionalfiction
    username: root
    password: admin123!
  elasticsearch:
    # elasticsearch文档数据库配置信息
    jest:
      uris: http://39.108.37.4:9200
  mail:
    # 邮件发送功能相关配置
    username: 2669868310@qq.com
    password: qskebolxewljdijh
    host: smtp.qq.com
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
#logging:
#  level:
#    com.huankong.fictionalfiction.mapper: debug
---
spring:
  profiles: prd
  redis:
    # redis缓存配置信息
    host: 127.0.0.1
    port: 6379
  datasource:
    # mysql数据库配置信息
    url: jdbc:mysql://127.0.0.1:3306/db_fictionalfiction
    username: root
    password: admin123!
  elasticsearch:
    # elasticsearch文档数据库配置信息
    jest:
      uris: http://127.0.0.1:9200
